Add `-Wno-unused-variable` flag to OS X clang flag
Without this flag, it's unable to compile libv8 on OS X 10.10 due to
this error message:

    ruby ext/libv8/extconf.rb
    creating Makefile
    HEAD is now at 7ce3fe1... Version 3.16.14
    Using existing [svn-remote "svn"]
    HEAD is now at f7bc250... Make gyp/win32 compatible with upstream ninja.
    Compiling v8 for x64
    Using python 2.7.6
    Using compiler: /usr/bin/c++ (clang version 5.1)
    ../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
    static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
                     ^
    1 error generated.
    make[1]: *** [/Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
    make: *** [x64.release] Error 2
    GYP_GENERATORS=make \
            build/gyp/gyp --generator-output="out" build/all.gyp \
                          -Ibuild/standalone.gypi --depth=. \
                          -Dv8_target_arch=x64 \
                          -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
      CXX(target) /Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
      CXX(target) /Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
      CXX(target) /Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
      CXX(target) /Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
      CXX(target) /Users/sikachu/Projects/libv8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o

This has been tested against this version of clang and OS X:

    $ g++ -v
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
    Target: x86_64-apple-darwin14.0.0
    Thread model: posix

This should fix #123