Add patch to allow build with clang 7.3
This adds the -Wno-shift-negative-value flag to Clang. Clang 7.3 was introduced
in OSX with XCode 7.3.

Without this flag, compiling with Clang 7.3 fails with errors such as:

    In file included from ../src/elements.h:32:
    ../src/objects.h:5252:44: error: shifting a negative signed value is undefined
    [-Werror,-Wshift-negative-value]
      static const int kElementsKindMask = (-1 << kElementsKindShift) &
                                            ~~ ^
    ../src/objects.h:7386:36: error: shifting a negative signed value is undefined
    [-Werror,-Wshift-negative-value]
          (~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    2 errors generated.